### ISSUE TITLE
Refactor server routes to remove "dynamic" generation and utilize express.Router()

### ISSUE THREAD

**Issue by WesTyler** [wafers/modulo#251]

**Comment by voxlol** [comment]
:( I knew that was a bad idea back in the day

**Comment by WesTyler** [comment]
@voxlol Haha, also we weren't taking advantage of express.router, which is more expressive and clear. Doing the auto-generation doesn't follow the .router method paradigm. :)

**Comment by voxlol** [comment]
haha yep. We did a lot of things incorrectly back at makersquare...I wish they had a lecture on best practices!

**Comment by quikstrike** [comment]
Solved in PR #253.
